apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-msvo
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-msvo@sha256:26826a7d1bb2b2154603d3680169b6f6114c7bde3c11c1a90fb247bf50f3cc37
        name: my-nodejs
        resources: {}
status: {}
